const countries = {
    "am-ET": "Amharic",
    "ar-SA": "Ả Rập",
    "be-BY": "Belarus",
    "bem-ZM": "Bemba",
    "bi-VU": "Bislama",
    "bjs-BB": "Bajan",
    "bn-IN": "Bengali",
    "bo-CN": "Tây Tạng",
    "br-FR": "Breton",
    "bs-BA": "Bosnia",
    "ca-ES": "Catalan",
    "cop-EG": "Coptic",
    "cs-CZ": "Séc",
    "cy-GB": "Wales",
    "da-DK": "Đan Mạch",
    "dz-BT": "Dzongkha",
    "de-DE": "Đức",
    "dv-MV": "Maldives",
    "el-GR": "Hy lạp",
    "en-GB": "Anh",
    "es-ES": "Tây Ban Nha",
    "et-EE": "Estonia",
    "eu-ES": "Basque",
    "fa-IR": "Ba Tư",
    "fi-FI": "Phần Lan",
    "fn-FNG": "Fanagalo",
    "fo-FO": "Faroe",
    "fr-FR": "Pháp",
    "gl-ES": "Galicia",
    "gu-IN": "Gujarati",
    "ha-NE": "Hausa",
    "he-IL": "Do Thái",
    "hi-IN": "Ấn Độ",
    "hr-HR": "Croatia",
    "hu-HU": "Hungary",
    "id-ID": "Indonesia",
    "is-IS": "Iceland",
    "it-IT": "Ý",
    "ja-JP": "Nhật",
    "kk-KZ": "Kazakh",
    "km-KM": "Khmer",
    "kn-IN": "Kannada",
    "ko-KR": "Hàn",
    "ku-TR": "Kurd",
    "ky-KG": "Kyrgyz",
    "la-VA": "La-tinh",
    "lo-LA": "Lào",
    "lv-LV": "Latvia",
    "men-SL": "Mende",
    "mg-MG": "Malagasy",
    "mi-NZ": "Maori",
    "ms-MY": "Mã Lai",
    "mt-MT": "Malta",
    "my-MM": "Miến Điện",
    "ne-NP": "Nepal",
    "niu-NU": "Niue",
    "nl-NL": "Hà Lan",
    "no-NO": "Na Uy",
    "ny-MW": "Chewa",
    "ur-PK": "Pakistan",
    "pau-PW": "Palau",
    "pa-IN": "Punjab",
    "ps-PK": "Pashto",
    "pis-SB": "Pijin",
    "pl-PL": "Ba Lan",
    "pt-PT": "Bồ Đào Nha",
    "rn-BI": "Kirundi",
    "ro-RO": "Roma(La Mã)",
    "ru-RU": "Nga",
    "sg-CF": "Sango",
    "si-LK": "Sinhala",
    "sk-SK": "Slovak",
    "sm-WS": "Samoa",
    "sn-ZW": "Shona",
    "so-SO": "Somali",
    "sq-AL": "Albania",
    "sr-RS": "Séc-bia",
    "sv-SE": "Thụy Điển",
    "sw-SZ": "Swahili",
    "ta-LK": "Tamil",
    "te-IN": "Telugu",
    "tet-TL": "Tetum",
    "tg-TJ": "Tajik",
    "th-TH": "Thái",
    "ti-TI": "Tigrinya",
    "tk-TM": "Turkmen",
    "tl-PH": "Tagalog",
    "tn-BW": "Tswana",
    "to-TO": "Tongan",
    "tr-TR": "Thổ Nhĩ Kỳ",
    "uk-UA": "Ukraina",
    "uz-UZ": "Uzbek",
    "vi-VN": "Việt",
    "wo-SN": "Wolof",
    "xh-ZA": "Xhosa(Nam Phi)",
    "yi-YD": "Yiddish",
    "zu-ZA": "Zulu"
}